<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rdriver extends MY_Controller {

	protected $access = array('SuperAdmin','Admin','User');

    function __construct()
    {
        parent::__construct();

		$this->load->model('Master');
        $this->load->model('Rdriver_model');
        $this->load->library('form_validation');
		//$this->load->library('datatables');
		//$this->load->library('M_pdf');
    }

    public function index()
    {
	     //$Rdriver = $this->Rdriver_model->get_all();

 		$data = array(
            'button' => 'Generate',
            'action' => site_url('Rdriver/calc'),
			'generator' =>set_value('')
		);

		//$combo['query']= $this->Master->getdriver("");

		$this->load->view('header');
        $this->load->view('Rdriver/Rdriver_head');
		$this->load->view('Rdriver/Rdriver_list');
        $this->load->view('footer'); 

		//$this->hitung();
    }

		public function hitung(){

		$filename = time()."_order.pdf";


		$arg = array(
			'dari' => date("Y-m-d",strtotime(substr($this->input->post('tanggal',TRUE),0,10))),
			'sampai' => date("Y-m-d",strtotime(substr($this->input->post('tanggal',TRUE),13,10))),
		);


		$data['query'] = $this->Rdriver_model->getschedule($arg);

		$this->load->view('header');
		$this->load->view('Rdriver/Rdriver_head');
		$this->load->view('Rdriver/Rdriver_list',$data);
		$this->load->view('footer');
	}

    public function generate(){

		$datahead = array(
            'button' => 'Generate',
            'action' => site_url('generate'),
			'generator' => "1"
		);

		$data = array(
			'Tanggal' => date("Y-m-d",strtotime($this->input->post('Tanggal',TRUE))),
			'iddriver' => $this->input->post('iddriver',TRUE),
		);



		$data = $this->Rdriver_model->get_by_drivertanggal($data);
		$combo['query']= $this->Master->getdriver("");

		$this->load->view('header',$combo);
		$this->load->view('Rdriver/Rdriver_head',$datahead);
		$this->load->view('Rdriver/Rdriver_list',$data);
        $this->load->view('footer');


	}

    public function json() {
        header('Content-Type: application/json');
        echo $this->Rdriver_model->json();
    }



    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "Rdriver.xls";
        $judul = "Rdriver";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
	xlsWriteLabel($tablehead, $kolomhead++, "Tanggal");
	xlsWriteLabel($tablehead, $kolomhead++, "Jam");
	xlsWriteLabel($tablehead, $kolomhead++, "Tujuan");
	xlsWriteLabel($tablehead, $kolomhead++, "Iddriver");
	xlsWriteLabel($tablehead, $kolomhead++, "User");
	xlsWriteLabel($tablehead, $kolomhead++, "Status");

	foreach ($this->Rdriver_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteLabel($tablebody, $kolombody++, $data->Tanggal);
	    xlsWriteLabel($tablebody, $kolombody++, $data->Jam);
	    xlsWriteLabel($tablebody, $kolombody++, $data->Tujuan);
	    xlsWriteNumber($tablebody, $kolombody++, $data->iddriver);
	    xlsWriteNumber($tablebody, $kolombody++, $data->User);
		xlsWriteNumber($tablebody, $kolombody++, $data->Status);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=Rdriver.doc");

        $data = array(
            'Rdriver_data' => $this->Rdriver_model->get_all(),
            'start' => 0
        );

        $this->load->view('Rdriver/Rdriver_doc',$data);
    }

}

/* End of file Rdriver.php */
/* Location: ./application/controllers/Rdriver.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-10 04:19:34 */
/* http://harviacode.com */
