<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rdriver_model extends CI_Model
{

    public $table = 'tschedule';
	//public $query = 'tschedule';
	public $query = "select Tanggal,Jam,Tujuan,Tdriver.Nama as driver, user.nama as pengguna from Tschedule,Tdriver,user where Tschedule.iddriver=Tdriver.iddriver and Tschedule.User = user.id and Tschedule.status=1";
    public $id = 'ID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
	
		function getschedule($data){
		
		//$query = $this->db->query("select Tanggal,Jam,Tujuan,Tdriver.Nama as driver, user.nama as pengguna from Tschedule,Tdriver,user where Tschedule.iddriver=Tdriver.iddriver and Tschedule.User = user.id and Tschedule.status=1 and Tschedule.iddriver=".$driver." and Tschedule.tanggal='".$tanggal."'");
		//$kondisi = "Tschedule.Tanggal between '".$data['dari']."' and '". $data['sampai']."'";
		//$query = $this->db->query("select Tanggal,Jam,Tujuan,Tdriver.Nama as driver, user.nama as pengguna from Tschedule,Tdriver,user where Tschedule.iddriver=Tdriver.iddriver and Tschedule.User = user.id and Tschedule.status=1 and " .$kondisi );
		
		 $this->db->select('Tanggal,tdriver.Nama as Driver,Masuk,Pulang,Tipe');
		$this->db->from('tinbound');
		$this->db->join('tdriver','tinbound.iddriver = tdriver.iddriver');
		$this->db->where('Tanggal >=',$data['dari']);
		$this->db->where('Tanggal <=',$data['sampai']);
		$this->db->order_by('Tanggal');
		$query = $this->db->get();
		 
		 return $query->result();
		
	}
	
	function getdriver($driver,$tanggal){
		
		$query = $this->db->query("select Tanggal,Jam,Tujuan,Tdriver.Nama as driver, user.nama as pengguna from Tschedule,Tdriver,user where Tschedule.iddriver=Tdriver.iddriver and Tschedule.User = user.id and Tschedule.status=1 and Tschedule.iddriver=".$driver." and Tschedule.tanggal='".$tanggal."'");
		return $query->result();
		
	}
	
    // datatables
    function json() {
        $this->datatables->select('DATE_FORMAT(Tanggal, "%d-%m-%Y") as Tanggal,Jam,Tujuan,Tdriver.nama as driver,User.nama as pengguna');
        $this->datatables->from('tschedule');
        //add this line for join
        $this->datatables->join('tdriver', 'tschedule.iddriver = tdriver.iddriver');
		$this->datatables->join('user', 'tschedule.user = user.id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $query = $this->db->query("select Tanggal,Jam,Tujuan,Tdriver.Nama as driver, user.nama as pengguna from Tschedule,Tdriver,user where Tschedule.iddriver=Tdriver.iddriver and Tschedule.User = user.id and Tschedule.status=1 ");
		return $query->result();
    }

    // generate report 
    function get_by_drivertanggal($data)
    { 
	
     $Tanggal = $data['Tanggal'];
	 $iddriver = $data['iddriver'];
	 
	 if ($Tanggal!=null and $iddriver!=null){
		 $kondisi = " and Tschedule.iddriver=".$iddriver." and Tschedule.tanggal='".$Tanggal."'";
	 }else if ($Tanggal==null and $iddriver!=null){
		 $kondisi = " and Tschedule.iddriver=".$iddriver ;
	 }else if ($Tanggal!=null and $iddriver==null){
		 $kondisi = " and Tschedule.tanggal='".$Tanggal."'";
	 } else {
		 $kondisi = "";
	 }
		
		$query = $this->db->query("select Tanggal,Jam,Tujuan,Tdriver.Nama as driver, user.nama as pengguna from Tschedule,Tdriver,user where Tschedule.iddriver=Tdriver.iddriver and Tschedule.User = user.id and Tschedule.status=1 ".$kondisi);
		return $query->result();
		
		
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID', $q);
	$this->db->or_like('Tanggal', $q);
	$this->db->or_like('Jam', $q);
	$this->db->or_like('Tujuan', $q);
	$this->db->or_like('iddriver', $q);
	$this->db->or_like('User', $q);
	$this->db->or_like('Status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID', $q);
	$this->db->or_like('Tanggal', $q);
	$this->db->or_like('Jam', $q);
	$this->db->or_like('Tujuan', $q);
	$this->db->or_like('iddriver', $q);
	$this->db->or_like('User', $q);
	$this->db->or_like('Status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

   
   

}

/* End of file Rdriver_model.php */
/* Location: ./application/models/Rdriver_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-10 04:19:34 */
/* http://harviacode.com */