<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tinbound_model extends CI_Model
{

    public $table = 'tinbound';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,tdriver.Nama as iddriver,Tanggal,Tipe,Masuk,Pulang');
        $this->datatables->from('tinbound');
        //add this line for join
		$this->datatables->join('tdriver', 'tinbound.iddriver = tdriver.iddriver');
        $this->datatables->add_column('action', anchor(site_url('tinbound/read/$1'),'Read')." | ".anchor(site_url('tinbound/update/$1'),'Update')." | ".anchor(site_url('tinbound/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('tdriver','tinbound.iddriver = tdriver.iddriver');
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('iddriver', $q);
	$this->db->or_like('Tanggal', $q);
	$this->db->or_like('Masuk', $q);
	$this->db->or_like('Pulang', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('iddriver', $q);
	$this->db->or_like('Tanggal', $q);
	$this->db->or_like('Masuk', $q);
	$this->db->or_like('Pulang', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tinbound_model.php */
/* Location: ./application/models/Tinbound_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-01 17:36:16 */
/* http://harviacode.com */
