<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tschedule_model extends CI_Model
{

    public $table = 'tschedule';
    public $id = 'ID';
    public $order = 'DESC';
    public $tanggal = 'Tanggal';
    public $status= 'Status';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {

        $this->datatables->select('tschedule.ID,DATE_FORMAT(tschedule.Tanggal, "%d-%m-%Y") as Tanggal,tschedule.Jam,tschedule.Tujuan,tdriver.Nama as iddriver,user.nama as User ,tschedule.Status');
        $this->datatables->from('tschedule');
        //add this line for join
        $this->datatables->join('tdriver', 'tschedule.iddriver = tdriver.iddriver');
		$this->datatables->join('user', 'tschedule.user = user.id');
		//$this->datatables->where

		if ($this->session->userdata('role')=='User'){
			$this->db->where('user', $this->session->userdata('id'));
		}

        $this->datatables->add_column('action', anchor(site_url('tschedule/read/$1'),'Read')." | ".anchor(site_url('tschedule/update/$1'),'Update')." | ".anchor(site_url('tschedule/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'ID');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

	// get by user
    function get_byuser()
    {
		//$user = $this->session->userdata('id');

		$this->db->where('user', $this->session->userdata('id'));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {

		$this->db->select('ID,DATE_FORMAT(Tanggal, "%d-%m-%Y") as Tanggal,Jam,Tujuan,tdriver.iddriver ,Nama as namadriver,User,Status');
		$this->db->from($this->table);
		$this->db->join('tdriver', 'tschedule.iddriver = tdriver.iddriver');
		//$query = $this->db->get();
        $this->db->where($this->id, $id);
        return $this->db->get()->row();
    }


	   function get_excel()
    {

		$this->db->select('tschedule.ID,DATE_FORMAT(tschedule.Tanggal, "%d-%m-%Y") as Tanggal,tschedule.Jam,tschedule.Tujuan,tdriver.Nama as iddriver,user.nama as User ,tschedule.Status');
		$this->db->from($this->table);
		$this->db->join('tdriver', 'tschedule.iddriver = tdriver.iddriver');
		//$query = $this->db->get();
        $this->db->where($this->id, $id);
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('ID', $q);
      	$this->db->or_like('Tanggal', $q);
      	$this->db->or_like('Jam', $q);
      	$this->db->or_like('Tujuan', $q);
      	$this->db->or_like('iddriver', $q);
      	$this->db->or_like('User', $q);
      	$this->db->or_like('Status', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID', $q);
      	$this->db->or_like('Tanggal', $q);
      	$this->db->or_like('Jam', $q);
      	$this->db->or_like('Tujuan', $q);
      	$this->db->or_like('iddriver', $q);
      	$this->db->or_like('User', $q);
      	$this->db->or_like('Status', $q);
      	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_bydate($date)
    {
      $this->db->select('ID');
      $this->db->from($this->table);
      $this->db->where('Tanggal <', $date);
      $this->db->where("Status", 0);
      return $this->db->get()->result();
    }

}

/* End of file Tschedule_model.php */
/* Location: ./application/models/Tschedule_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-10 04:19:34 */
/* http://harviacode.com */
